# Generated by Django 3.1.1 on 2020-09-29 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0002_auto_20200928_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_likes',
            field=models.ManyToManyField(related_name='web_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
